### PR TITLE
DM-30113: LDM-503-RSPa done / DMTR-381 ready for review

### PR DESCRIPTION
**Pull request by gpdf**

### CODE REVIEW

**Review by womullan — APPROVED** [review]
looks good thanks

**Review by leannep — APPROVED** [review]
Minor comment - the layout does not follow the standard of a new line per sentence.

**Comment by gpdf** [comment]
> Minor comment - the layout does not follow the standard of a new line per sentence.

You mean, in the LaTeX source?  Is that really feasible for LaTeX that comes from a Jira extraction?

**Comment by womullan** [comment]
i guess it never complied - you can put a ticket on docsteady for that and at some point i can go through the templates.

**Comment by womullan** [comment]
that said it may not be so simple for blocks of text which come from Jira .. currently they are barely processed this would require inserting linefeed.

**Comment by gpdf** [comment]
I really don't think auto-generated LaTeX needs to confirm to the project standard.  That said, it _does_ make reviewing small changes easier.  I can make a ticket, but it's going to be a very low priority - getting the "requirements verified" fields into the test reports is more important.

**Comment by leannep** [comment]
Yes, it makes reviewing easier - that is the goal, but this  is not a blocker for this PR.  A ticket is fine to followup later

**Comment by gpdf** [comment]
The test report has been updated to use status values in a way that has been agreed with @leannep, Jeff Carlin, and Austin Roberts.  Most importantly, we have changed to not assign "Pass with Deviation" to any of the issues noted during testing, as this status is only to be used for deviations from requirements which we intend as final and not to be further addressed.

We have used "Initial Pass" for test steps where the results were reasonable but not adequately conformant to the requirement.  This status prevents the completion of the verification activity for the requirement for now, but can be relieved by a subsequent "Pass".

Requesting a re-review from @leannep .

**Comment by gpdf** [comment]
Note that, following the approval and issuing of this test report, we will recast the entire report in a different way in Jira to avoid some unintended consequences of the way tests were combined into test cases in this test plan, which are causing problems downstream in the verification workflow.

**Review by leannep — APPROVED** [review]
Excellent work

**Pull request merged**
